/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduleplanner;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import scheduleplanner.Authentication.course;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xwpf.usermodel.*;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTRow;
import org.apache.commons.compress.archivers.zip.ZipFile;


/**
 *
 * @author Matthew_PC
 */
public class CourseTakenCS extends javax.swing.JPanel {
    
    static ArrayList<Authentication.course> core, mathMinor, csElectives, singleClassElectives, 
            languagesElectives, theoElectives, philoElectives, 
            humElectives, fineArtsElectives, scienceElectives;

    /**
     * Creates new form CourseTakenCS
     */
    public Operations op = new Operations();
    public CourseTakenCS() {
        initComponents();
        
        //calls the transcript from the Authentication class
        ArrayList<Authentication.course> transcript = (ArrayList<Authentication.course>) Authentication.transcript.clone();
        
        /*Anything with a .createWhatever creates an ArrayList<course> of the Whatever*/
        core = CourseRequirementsCS.createCore();
        op.printList(op.courseTaken(corelbl, 38.00,core, transcript), coretxt);
 
        csElectives = CourseRequirementsCS.createCSElectives();
        op.printList(op.courseTaken(eleclbl, 12.00,csElectives, transcript), electxt);
        
        mathMinor = CourseRequirementsCS.createMathMinor();
        op.printList(op.courseTaken(mathlbl, 20.00,mathMinor, transcript), mathtxt);
        
        scienceElectives = CourseRequirementsCS.createScienceElectives();
        op.printList(op.courseTaken(physlbl, 8.00, scienceElectives, transcript), phystxt);
        
        philoElectives = CourseRequirementsCS.createPhiloElectives();
        op.printList(op.courseTaken(phillbl, 3.00, philoElectives, transcript), philtxt);
        
        languagesElectives = CourseRequirementsCS.createLanguagesElectives();
        op.printList(op.courseTaken(forelbl, 3.00, languagesElectives, transcript), foretxt);
        
        singleClassElectives = CourseRequirementsCS.createSingleClassElectives();
        op.printList(op.courseTaken(genelbl, 27.00, singleClassElectives, transcript), genetxt);
        
        fineArtsElectives = CourseRequirementsCS.createFineArtsElectives();
        op.printList(op.courseTaken(finelbl, 3.00, fineArtsElectives, transcript), finetxt);
        
        humElectives = CourseRequirementsCS.createHumLitElectives();
        op.printList(op.courseTaken(humalbl, 3.00, humElectives, transcript), humatxt);
        
        theoElectives = CourseRequirementsCS.createTheoElectives();
        op.printList(op.courseTaken(theolbl, 3.00, theoElectives, transcript), theotxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        corelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coretxt = new javax.swing.JTextArea();
        eleclbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        electxt = new javax.swing.JTextArea();
        mathlbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mathtxt = new javax.swing.JTextArea();
        physlbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        phystxt = new javax.swing.JTextArea();
        forelbl = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        foretxt = new javax.swing.JTextArea();
        finelbl = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        finetxt = new javax.swing.JTextArea();
        theolbl = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        theotxt = new javax.swing.JTextArea();
        phillbl = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        philtxt = new javax.swing.JTextArea();
        humalbl = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        humatxt = new javax.swing.JTextArea();
        genelbl = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        genetxt = new javax.swing.JTextArea();
        createDoc = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Courses Taken Per Major Subsection");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 270, -1));

        corelbl.setText("Major Core Courses");
        add(corelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, -1, -1));

        coretxt.setColumns(20);
        coretxt.setRows(5);
        jScrollPane1.setViewportView(coretxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 416, 82));

        eleclbl.setText("Major Electives");
        add(eleclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));

        electxt.setColumns(20);
        electxt.setRows(5);
        jScrollPane2.setViewportView(electxt);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 202, 416, 79));

        mathlbl.setText("Mathematics Minor");
        add(mathlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, -1, -1));

        mathtxt.setColumns(20);
        mathtxt.setRows(5);
        jScrollPane3.setViewportView(mathtxt);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, 416, 73));

        physlbl.setText("Physics Requirement");
        add(physlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        phystxt.setColumns(20);
        phystxt.setRows(5);
        jScrollPane4.setViewportView(phystxt);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 416, 67));

        forelbl.setText("Foreign Language Requirement");
        add(forelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 515, -1, -1));

        foretxt.setColumns(20);
        foretxt.setRows(5);
        jScrollPane5.setViewportView(foretxt);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 535, 416, 78));

        finelbl.setText("Fine Art Requirement");
        add(finelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 48, -1, -1));

        finetxt.setColumns(20);
        finetxt.setRows(5);
        jScrollPane7.setViewportView(finetxt);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 68, 416, 78));

        theolbl.setText("Theology Requirement");
        add(theolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 164, -1, -1));

        theotxt.setColumns(20);
        theotxt.setRows(5);
        jScrollPane8.setViewportView(theotxt);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 184, 416, 78));

        phillbl.setText("Philosophy Requirement");
        add(phillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 280, -1, -1));

        philtxt.setColumns(20);
        philtxt.setRows(5);
        jScrollPane9.setViewportView(philtxt);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 300, 416, 78));

        humalbl.setText("Humanities Requirement");
        add(humalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 396, -1, -1));

        humatxt.setColumns(20);
        humatxt.setRows(5);
        jScrollPane10.setViewportView(humatxt);

        add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 416, 416, 78));

        genelbl.setText("General Ed Requirements");
        add(genelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 512, 416, -1));

        genetxt.setColumns(20);
        genetxt.setRows(5);
        jScrollPane6.setViewportView(genetxt);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 532, 416, 81));

        createDoc.setText("Create Document");
        createDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDocActionPerformed(evt);
            }
        });
        add(createDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDocActionPerformed
        // TODO add your handling code here:
        ArrayList<Authentication.course> transcript = (ArrayList<Authentication.course>) Authentication.transcript.clone();
        XWPFDocument doc;
        try{
            
            /*Please do not mess with this either! Ff you have to, make sure that you call 
            the FileTypeFilter class correctly*/
            
            //creates a file
            File fe = null;
            //allows you to choose a file
            JFileChooser fs = new JFileChooser((new File("c:\\Users")));
            //a filter for the kinds of file you can see and make(See FileTypeFilter class documentation)
            fs.setFileFilter(new FileTypeFilter(".docx","Word Document"));
            int result = fs.showSaveDialog(null);
            //if nothing goes wrong you can give the file a cool name, like Sprinkles
            //and create the file
            if(result == JFileChooser.APPROVE_OPTION){
                String temp = fs.getSelectedFile().toString();
                fe = new File(temp + ".docx");
            }
            
            //creates the actual Word document
            doc = new XWPFDocument();
            
            //Creates the core subsection in the document
            //See the Operations Class Documentation for Operation method calls
            FileOutputStream out = new FileOutputStream(fe);
            core = CourseRequirementsCS.createCore();
            op.createDocumentAudit("Core",core, transcript, doc);

            //Creates the CS Electives subsection in the document
            //See the Operations Class Documentation for Operation method calls
            csElectives = CourseRequirementsCS.createCSElectives();
            op.createDocumentAudit("Electives", csElectives, transcript, doc);

            //Creates the Math Minor subsection in the document
            //See the Operations Class Documentation for Operation method calls
            mathMinor = CourseRequirementsCS.createMathMinor();
            op.createDocumentAudit("Math Minor",mathMinor, transcript, doc);

            //Creates the Physics Requirement subsection in the document
            //See the Operations Class Documentation for Operation method calls
            scienceElectives = CourseRequirementsCS.createScienceElectives();
            op.createDocumentAudit("Physics Requirement", scienceElectives, transcript, doc);
            
            /* ***DO NOT FORGET THIS*** THIS CLOSES THE DOCUMENT AFTER YOU ARE DONE
            IF YOU FORGET THIS THE DOCUMENT WILL STAY OPEN AND PROBABLY DO A LOOP FOREVER
            THIS ***WILL*** CRASH YOUR PC, TRUST ME, YOUR PC WILL NOT HANDLE IT*/
            doc.write(out);
            out.close();
            doc.close();
            
        }catch(IOException e){
            //you gotta error handle
            System.out.println(e);
        }
    }//GEN-LAST:event_createDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel corelbl;
    private javax.swing.JTextArea coretxt;
    private javax.swing.JButton createDoc;
    private javax.swing.JLabel eleclbl;
    private javax.swing.JTextArea electxt;
    private javax.swing.JLabel finelbl;
    private javax.swing.JTextArea finetxt;
    private javax.swing.JLabel forelbl;
    private javax.swing.JTextArea foretxt;
    private javax.swing.JLabel genelbl;
    private javax.swing.JTextArea genetxt;
    private javax.swing.JLabel humalbl;
    private javax.swing.JTextArea humatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel mathlbl;
    private javax.swing.JTextArea mathtxt;
    private javax.swing.JLabel phillbl;
    private javax.swing.JTextArea philtxt;
    private javax.swing.JLabel physlbl;
    private javax.swing.JTextArea phystxt;
    private javax.swing.JLabel theolbl;
    private javax.swing.JTextArea theotxt;
    // End of variables declaration//GEN-END:variables
}
