/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduleplanner;

import static scheduleplanner.Authentication.tran;

/**
 *
 * @author Matthew_PC
 */
public class MainWindow extends javax.swing.JDialog {
    public static String[] columnNames = {"Term","Prefix","Number","Course Name","Credits","Grade"};
    
    //Takes the string from the dropdown menu
    String major = LoginDialog.major;
    //creates multiple Panes to put into the tabs of the main window
    public javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public javax.swing.JTable tran = new javax.swing.JTable();
    public javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
    public javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        //Sets the first tab to a table of the transcript retrieved from Authentication
        System.out.println("MainWindow");
        jScrollPane1.setViewportView(tran);
        jTabbedPane1.add("Transcript", jScrollPane1);
        
        
        //Checks the name of the major and executes appropriate operations and sets the tabs appropriately
        switch(LoginDialog.major) {
          case "Biology - Professional":
            CourseRequirementsBIOP crBIOP = new CourseRequirementsBIOP();
            crBIOP.setVisible(true);
            CourseTakenBIOP ctBIOP = new CourseTakenBIOP();
            ctBIOP.setVisible(true);
            jScrollPane2.setViewportView(crBIOP);
            jTabbedPane1.add("Remaining Courses", jScrollPane2);
            jScrollPane3.setViewportView(ctBIOP);
            jTabbedPane1.add("Courses Taken", jScrollPane3);
            break;
          case "Computer Science":
            CourseRequirementsCS crCS = new CourseRequirementsCS();
            crCS.setVisible(true);
            CourseTakenCS ctCS = new CourseTakenCS();
            ctCS.setVisible(true);
            jScrollPane2.setViewportView(crCS);
            jTabbedPane1.add("Remaining Courses", jScrollPane2);
            jScrollPane3.setViewportView(ctCS);
            jTabbedPane1.add("Courses Taken", jScrollPane3);
            break;
          case "Biology - General":
            CourseRequirementsBIOT crBIOT = new CourseRequirementsBIOT();
            crBIOT.setVisible(true);
            CourseTakenBIOT ctBIOT = new CourseTakenBIOT();
            ctBIOT.setVisible(true);
            jScrollPane2.setViewportView(crBIOT);
            jTabbedPane1.add("Remaining Courses", jScrollPane2);
            jScrollPane3.setViewportView(ctBIOT);
            jTabbedPane1.add("Courses Taken", jScrollPane3);
            break;
          case "Biology - Marine":
            CourseRequirementsBIOM crBIOM = new CourseRequirementsBIOM();
            crBIOM.setVisible(true);
            CourseTakenBIOM ctBIOM = new CourseTakenBIOM();
            ctBIOM.setVisible(true);
            jScrollPane2.setViewportView(crBIOM);
            jTabbedPane1.add("Remaining Courses", jScrollPane2);
            jScrollPane3.setViewportView(ctBIOM);
            jTabbedPane1.add("Courses Taken", jScrollPane3);
            break;
          default:
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("MainWindow"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow dialog = new MainWindow();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
